# Generated by Django 6.0.3 on 2026-03-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLibrary',
            fields=[
                ('libraryId', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('trackId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('genre', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('HIPHOP', 'Hip Hop'), ('CLASSICAL', 'Classical'), ('OTHER', 'Other')], max_length=50)),
                ('mood', models.CharField(max_length=100)),
                ('occasion', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed')], default='PROCESSING', max_length=50)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.musiclibrary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SharePermission',
            fields=[
                ('permissionId', models.AutoField(primary_key=True, serialize=False)),
                ('accessLevel', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('SHARE', 'Share')], max_length=50)),
                ('shareLink', models.URLField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_permissions', to='api.musictrack')),
            ],
        ),
        migrations.CreateModel(
            name='EmailInvitation',
            fields=[
                ('invitationId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired')], default='PENDING', max_length=50)),
                ('sentAt', models.DateTimeField(blank=True, null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.sharepermission')),
            ],
        ),
        migrations.AddField(
            model_name='musiclibrary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='api.user'),
        ),
        migrations.CreateModel(
            name='ListeningActivity',
            fields=[
                ('activityId', models.AutoField(primary_key=True, serialize=False)),
                ('playedAt', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(help_text='Duration played in seconds')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_activities', to='api.musictrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_activities', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='QUEUED', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_request', to='api.musictrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='api.user')),
            ],
        ),
    ]
