# Generated by Django 6.0.3 on 2026-04-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='suno_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='audio_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
