# Generated by Django 6.0.3 on 2026-04-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_generationrequest_suno_task_id_musictrack_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='negativeTags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='vocalGender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
