# Generated by Django 6.0.3 on 2026-04-24 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_generationrequest_negativetags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharepermission',
            name='track',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=50),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('HIDDEN', 'Hidden')], default='PROCESSING', max_length=50),
        ),
        migrations.CreateModel(
            name='TrackInvite',
            fields=[
                ('inviteId', models.AutoField(primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to='api.user')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='api.user')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.musictrack')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailInvitation',
        ),
        migrations.DeleteModel(
            name='SharePermission',
        ),
    ]
