# Generated by Django 6.0.3 on 2026-04-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sharepermission_track_musictrack_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='genre',
            field=models.CharField(max_length=255),
        ),
    ]
