# Generated by Django 6.0.3 on 2026-04-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_musictrack_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='musictrack',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='musictrack',
            name='occasion',
        ),
        migrations.DeleteModel(
            name='ListeningActivity',
        ),
    ]
