# Generated by Django 6.0.3 on 2026-04-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_musictrack_duration_remove_musictrack_mood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinvite',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('REMOVED', 'Removed')], default='PENDING', max_length=50),
        ),
    ]
