# Generated by Django 6.0.3 on 2026-04-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_trackinvite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
